### ISSUE TITLE
[Bug Report] There is a bug in the DPO training process.

### ISSUE THREAD

**Issue by xyzCS** [meowpass/FollowComplexInstruction#2]
Dear Author,

Thank you for making this excellent code available as open source.

I encountered an issue with line 118 in the dpo_train.py file: len_chosen = batch["chosen_labels"].shape[0]. It appears the batch does not contain the key "chosen_labels".

Could you please offer some guidance on how to resolve this?

Thank you.

**Comment by meowpass** [comment]
This error arises from the use of an incompatible version of the TRL package. In earlier versions of TRL (e.g., 0.7.11), the dataset was pre-processed using the **tokenize_row** function, which appended the "chosen_labels" field (can be seen in [line 727 of 0.7.11 release](https://github.com/huggingface/trl/blob/v0.7.11/trl/trainer/dpo_trainer.py). However, this function has since been revised in more recent versions. **A straightforward solution is to downgrade to an earlier version of TRL**. We strongly recommend creating a new environment using a requirements.txt file to prevent encountering similar issues in the future.

**Comment by xyzCS** [comment]
Thank you so much, I have addressed this issue!

> This error arises from the use of an incompatible version of the TRL package. In earlier versions of TRL (e.g., 0.7.11), the dataset was pre-processed using the **tokenize_row** function, which appended the "chosen_labels" field (can be seen in [line 727 of 0.7.11 release](https://github.com/huggingface/trl/blob/v0.7.11/trl/trainer/dpo_trainer.py). However, this function has since been revised in more recent versions. **A straightforward solution is to downgrade to an earlier version of TRL**. We strongly recommend creating a new environment using a requirements.txt file to prevent encountering similar issues in the future.
